USE [master]
GO

CREATE DATABASE [LuxFacta]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LuxFacta', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\LuxFacta.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LuxFacta_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\LuxFacta_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [LuxFacta] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LuxFacta].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LuxFacta] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LuxFacta] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LuxFacta] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LuxFacta] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LuxFacta] SET ARITHABORT OFF 
GO

ALTER DATABASE [LuxFacta] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LuxFacta] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LuxFacta] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LuxFacta] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LuxFacta] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LuxFacta] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LuxFacta] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LuxFacta] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LuxFacta] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LuxFacta] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LuxFacta] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LuxFacta] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LuxFacta] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LuxFacta] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LuxFacta] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LuxFacta] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LuxFacta] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LuxFacta] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [LuxFacta] SET  MULTI_USER 
GO

ALTER DATABASE [LuxFacta] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LuxFacta] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LuxFacta] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LuxFacta] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LuxFacta] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LuxFacta] SET QUERY_STORE = OFF
GO

USE [LuxFacta]
GO

ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [LuxFacta] SET  READ_WRITE 
GO


USE [LuxFacta]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Poll](
	[Poll_Id] [int] NOT NULL,
	[Poll_Description] [varchar](max) NOT NULL,
	[Poll_Views] [int] NOT NULL,
 CONSTRAINT [PK_Poll] PRIMARY KEY CLUSTERED 
(
	[Poll_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Poll] ADD  CONSTRAINT [DF_Poll_Poll_Views]  DEFAULT ((0)) FOR [Poll_Views]
GO

CREATE TABLE [dbo].[Options](
	[Opt_Id] [int] NOT NULL,
	[Opt_Poll_Id] [int] NOT NULL,
	[Opt_Description] [varchar](max) NOT NULL,
	[Opt_Votes] [int] NOT NULL,
 CONSTRAINT [PK_Options] PRIMARY KEY CLUSTERED 
(
	[Opt_Id] ASC,
	[Opt_Poll_Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[Options] ADD  CONSTRAINT [DF_Options_Opt_Votes]  DEFAULT ((0)) FOR [Opt_Votes]
GO

ALTER TABLE [dbo].[Options]  WITH CHECK ADD  CONSTRAINT [FK_Options_Poll] FOREIGN KEY([Opt_Poll_Id])
REFERENCES [dbo].[Poll] ([Poll_Id])
GO

ALTER TABLE [dbo].[Options] CHECK CONSTRAINT [FK_Options_Poll]
GO

CREATE SEQUENCE [dbo].[Seq_Poll] 
 AS [bigint]
 START WITH 1
 INCREMENT BY 1
 MINVALUE -9223372036854775808
 MAXVALUE 9223372036854775807
 CACHE 
GO
